---
- name: create /opt/ansible
  file:
    path: /opt/ansible
    state: directory

# - name: "create /opt/ansible/{{user_name}}"
#   file:
#     path: /opt/ansible
#     state: directory

- name: create /opt/ansible/users.yml
  file:
    path: /opt/ansible/users.yml
    state: touch

- set_fact:
    my_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

- debug:
    msg: "{{ user_name}}: {{ my_pass }}"

- name: Add user to users.yml
  lineinfile:
    path: /opt/ansible/users.yml
    line: "{{ user_name}}: {{ my_pass}}"

- name: Ensure group "somegroup" exists
  group:
    name: devops
    state: present

- name: Added user to admins
  user:
    name: '{{ user_name }}'
    password: "{{my_pass | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    generate_ssh_key: yes

- name:  get key
  shell: 'cat /home/{{user_name}}/.ssh/id_rsa.pub'
  register: user_ssh_key


- name:  Add public key  to users.yml
  lineinfile:
    path: /opt/ansible/users.yml
    line: "{{ user_name}}_ssh: {{ user_ssh_key.stdout }}"

- name: COPY
  fetch:
    src: /opt/ansible/users.yml
    dest: '{{ workspace}}/users.yml'
    flat: yes
      # expires: 1422403387
      # - name: Download foo.conf

# - name: Test ping host all
#   hosts: main_server
#   #become: yes
#   gather_facts: yes
# corp_servers
  # NOTE: Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
  # - name: Validate the sudoers file before saving
  #   ansible.builtin.lineinfile:
  #     path: /etc/sudoers
  #     state: present
  #     regexp: '^%ADMIN ALL='
  #     line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
  #     validate: /usr/sbin/visudo -cf %s
       #   get_url:
       # url: "{{ nodejs_url }}"
  #     dest: /opt/node.tar.xz
  #     mode: '0440'
  #
  # - name: tar.xz
  #   ansible.builtin.unarchive:
  #     src: /opt/node.tar.xz
  #     dest: /opt
  #     remote_src: yes
