---
- name: Ensure group "somegroup" exists
  group:
    name: devops
    state: present

- name: Added user to admins
  user:
    name: '{{ user_name }}'
    password: "{{lookup('file', '{{workspace}}/{{user_name}}.yml') }}"
    shell: /bin/bash
    groups: sudo
    generate_ssh_key: no


#authorize
- name: Set authorized key took from file
  authorized_key:
    user: '{{ user_name}}'
    state: present
    key: "{{lookup('file', '{{workspace}}/{{user_name}}_key.yml') }}"
  when: generate_ssh_key
