---
- name: Ensure group "somegroup" exists
  group:
    name: devops
    state: present

- name: generate_ssh_key
  debug:
    var: generate_ssh_key
- set_fact:
    my_pass:  "{{lookup('file', '{{workspace}}/{{user_name}}.yml') }}"

- name: Added user to admins
  user:
    name: '{{ user_name }}'
    password:  "{{my_pass | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    update_password: always
    generate_ssh_key: no


#authorize
- name: Set authorized key took from file
  authorized_key:
    user: '{{ user_name}}'
    state: present
    key: "{{lookup('file', '{{workspace}}/{{user_name}}_key.yml') }}"
  when: generate_ssh_key
